# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article_reco.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='article_reco.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x61rticle_reco.proto\"2\n\x07\x41rticle\x12\x12\n\narticle_id\x18\x01 \x01(\x05\x12\x13\n\x0b\x61rticle_num\x18\x02 \x01(\x05\"\x1b\n\x06param1\x12\x11\n\tsingle_id\x18\x01 \x03(\x05\"&\n\x01p\x12\x12\n\narticle_id\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\t\"\x1f\n\x06param2\x12\x15\n\tsingle_bp\x18\x01 \x03(\x0b\x32\x02.p\"Z\n\x0c\x42uried_point\x12#\n\x12\x61rticle_list_param\x18\x01 \x01(\x0b\x32\x07.param1\x12%\n\x14\x61rticle_single_param\x18\x02 \x01(\x0b\x32\x07.param22=\n\nARecommend\x12/\n\x12\x61rtilcle_recommend\x12\x08.Article\x1a\r.Buried_point\"\x00\x62\x06proto3')
)




_ARTICLE = _descriptor.Descriptor(
  name='Article',
  full_name='Article',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='article_id', full_name='Article.article_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article_num', full_name='Article.article_num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=72,
)


_PARAM1 = _descriptor.Descriptor(
  name='param1',
  full_name='param1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='single_id', full_name='param1.single_id', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=101,
)


_P = _descriptor.Descriptor(
  name='p',
  full_name='p',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='article_id', full_name='p.article_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='p.param', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=141,
)


_PARAM2 = _descriptor.Descriptor(
  name='param2',
  full_name='param2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='single_bp', full_name='param2.single_bp', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=174,
)


_BURIED_POINT = _descriptor.Descriptor(
  name='Buried_point',
  full_name='Buried_point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='article_list_param', full_name='Buried_point.article_list_param', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='article_single_param', full_name='Buried_point.article_single_param', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=266,
)

_PARAM2.fields_by_name['single_bp'].message_type = _P
_BURIED_POINT.fields_by_name['article_list_param'].message_type = _PARAM1
_BURIED_POINT.fields_by_name['article_single_param'].message_type = _PARAM2
DESCRIPTOR.message_types_by_name['Article'] = _ARTICLE
DESCRIPTOR.message_types_by_name['param1'] = _PARAM1
DESCRIPTOR.message_types_by_name['p'] = _P
DESCRIPTOR.message_types_by_name['param2'] = _PARAM2
DESCRIPTOR.message_types_by_name['Buried_point'] = _BURIED_POINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Article = _reflection.GeneratedProtocolMessageType('Article', (_message.Message,), dict(
  DESCRIPTOR = _ARTICLE,
  __module__ = 'article_reco_pb2'
  # @@protoc_insertion_point(class_scope:Article)
  ))
_sym_db.RegisterMessage(Article)

param1 = _reflection.GeneratedProtocolMessageType('param1', (_message.Message,), dict(
  DESCRIPTOR = _PARAM1,
  __module__ = 'article_reco_pb2'
  # @@protoc_insertion_point(class_scope:param1)
  ))
_sym_db.RegisterMessage(param1)

p = _reflection.GeneratedProtocolMessageType('p', (_message.Message,), dict(
  DESCRIPTOR = _P,
  __module__ = 'article_reco_pb2'
  # @@protoc_insertion_point(class_scope:p)
  ))
_sym_db.RegisterMessage(p)

param2 = _reflection.GeneratedProtocolMessageType('param2', (_message.Message,), dict(
  DESCRIPTOR = _PARAM2,
  __module__ = 'article_reco_pb2'
  # @@protoc_insertion_point(class_scope:param2)
  ))
_sym_db.RegisterMessage(param2)

Buried_point = _reflection.GeneratedProtocolMessageType('Buried_point', (_message.Message,), dict(
  DESCRIPTOR = _BURIED_POINT,
  __module__ = 'article_reco_pb2'
  # @@protoc_insertion_point(class_scope:Buried_point)
  ))
_sym_db.RegisterMessage(Buried_point)



_ARECOMMEND = _descriptor.ServiceDescriptor(
  name='ARecommend',
  full_name='ARecommend',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=268,
  serialized_end=329,
  methods=[
  _descriptor.MethodDescriptor(
    name='artilcle_recommend',
    full_name='ARecommend.artilcle_recommend',
    index=0,
    containing_service=None,
    input_type=_ARTICLE,
    output_type=_BURIED_POINT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARECOMMEND)

DESCRIPTOR.services_by_name['ARecommend'] = _ARECOMMEND

# @@protoc_insertion_point(module_scope)
